POST https://matkamonitori.digitransit.fi/api/graphql
accept: application/json
content-type: application/json
graphql-endpoint: routing/v2/finland/gtfs/v1

{
  "operationName": "GetDeparturesForStops",
  "variables": {
    "ids": ["MATKA:357184"],
    "numberOfDepartures": 4
  },
  "query": "query GetDeparturesForStops($ids: [String!]!, $numberOfDepartures: Int!) {\n  stops: stops(ids: $ids) {\n    gtfsId\n    name\n    alerts {\n      alertSeverityLevel\n      alertHeaderText\n      alertHeaderTextTranslations {\n        text\n        language\n        __typename\n      }\n      effectiveStartDate\n      effectiveEndDate\n      __typename\n    }\n    stoptimesForPatterns(numberOfDepartures: $numberOfDepartures, omitCanceled: false) {\n      pattern {\n        code\n        headsign\n        route {\n          shortName\n          longName\n          __typename\n        }\n        __typename\n      }\n      stoptimes {\n        serviceDay\n        scheduledDeparture\n        realtimeDeparture\n        realtimeState\n        __typename\n      }\n      __typename\n    }\n    __typename\n  }\n}"
}